Repository NavidRsh/argoumlFall2024, pull requests merged in 2024-11, with the labels that each got.

#20 Remove duplicate code from ActionAddClientDependencyAction.java and ActionAddSupplierDependencyAction.java
  src/argouml-app/src/org/argouml/uml/ui/AbstractActionAddModelElement2.java
  src/argouml-app/src/org/argouml/uml/ui/foundation/core/ActionAddClientDependencyAction.java
  src/argouml-app/src/org/argouml/uml/ui/foundation/core/ActionAddSupplierDependencyAction.java
Labels: Group 18

#21 remove code duplication in ToDoByGoal
  src/argouml-app/src/org/argouml/cognitive/ui/ToDoByGoal.java
Labels: Group 18, remove software clones

#23 Refactor Duplicate Code in ToDoByDecision.java
  src/argouml-app/src/org/argouml/cognitive/ui/ToDoByDecision.java
Labels: Group 18, remove software clones

#24 Clone Removal: Duplicated Code in FigConcurrentRegion.java
  .idea/.gitignore
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  src/argouml-app/src/org/argouml/uml/diagram/state/ui/FigConcurrentRegion.java
Labels: Group 18, remove software clones

#25 Refactor ToDoByType.java to Remove Duplicate Code in toDoItemsChanged and toDoItemsAdded
  src/argouml-app/src/org/argouml/cognitive/ui/ToDoByType.java
Labels: Group 18, remove software clones

#27 Fix security vulnerability reported by OWASP serializer-2.7.2.jar, xalan-2.7.2.jar and batik-css-1.14.jar
  src/argouml-app/pom.xml
Labels: Group 18

#28 Vulnerability removal "XML External Entity (XXE) Injection Issue #56"
  .gitignore
  .idea/argoumlFall2024.iml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/misc.xml
  .idea/workspace.xml
  src/argouml-app/tests/org/argouml/model/TestAgainstUmlModel.java
Labels: Group 18

#29 Fix SSRF Vulnerability in URL Handling
  src/argouml-core-model-mdr/src/org/argouml/model/mdr/XmiReferenceResolverImpl.java
Labels: Group 18

#32 Mitigate SSRF vulnerability by replacing URL-based stream access with secure ZipInputStream handling
  src/argouml-app/src/org/argouml/persistence/ZargoFilePersister.java
Labels: Group 18

#33 fix #75 - fix the XML parsing vulnerability to XXE in XmiReaderImpl c…
  src/argouml-core-model-mdr/src/org/argouml/model/mdr/XmiReaderImpl.java
Labels: Group 18, Removing Software Vulnerabilities
